In [ ]:
import pandas as pd
df = pd.read_csv('agora.csv')
df.describe()
df.head()

In [100]:
# Features Transformation Normalization
from sklearn.preprocessing import MinMaxScaler

m = MinMaxScaler()
markrting_speed_fit  = m.fit(df[['Marketing Spend']]) # trianing model 

df['transformed'] = m.transform(df[['Marketing Spend']]) # transferred to data frame

In [60]:

m_ = MinMaxScaler(feature_range=(5,10))
markrting_speed_fit_  = m_.fit(df[['Marketing Spend']]) 

df['transformed_2'] = m_.transform(df[['Marketing Spend']])


Marketing Spend 
 Administration 
 Transport 
 Area 
 Profit 
 transformed 
 transformed_2 
 
 
 
 
 0 
 114523.61 
 136897.80 
 471784.10 
 Dhaka 
 192261.83 
 0.692617 
 8.463083 
 
 
 1 
 162597.70 
 151377.59 
 443898.53 
 Ctg 
 191792.06 
 0.983359 
 9.916797 
 
 
 2 
 153441.51 
 101145.55 
 407934.54 
 Rangpur 
 191050.39 
 0.927985 
 9.639923 
 
 
 3 
 144372.41 
 118671.85 
 383199.62 
 Dhaka 
 182901.99 
 0.873136 
 9.365682 
 
 
 4 
 142107.34 
 91391.77 
 366168.42 
 Rangpur 
 166187.94 
 0.859438 
 9.297189 
 
 
 5 
 131876.90 
 99814.71 
 362861.36 
 Dhaka 
 156991.12 
 0.797566 
 8.987830 
 
 
 6 
 134615.46 
 147198.87 
 127716.82 
 Ctg 
 156122.51 
 0.814128 
 9.070641 
 
 
 7 
 130298.13 
 145530.06 
 323876.68 
 Rangpur 
 155752.60 
 0.788018 
 8.940090 
 
 
 8 
 120542.52 
 148718.95 
 311613.29 
 Dhaka 
 152211.77 
 0.729018 
 8.645089 
 
 
 9 
 123334.88 
 108679.17 
 304981.62 
 Ctg 
 149759.96 
 0.745906 
 8.729528 
 
 
 10 
 101913.08 
 110594.11 
 229160.95 
 Rangpur 
 146121.95 
 0.616351 
 8.081753 
 
 
 11 
 100671.96 
 91790.61 
 249744.55 
 Ctg 
 144259.40 
 0.608845 
 8.044223 
 
 
 12 
 93863.75 
 127320.38 
 249839.44 
 Rangpur 
 141585.52 
 0.567670 
 7.838349 
 
 
 13 
 91992.39 
 135495.07 
 252664.93 
 Ctg 
 134307.35 
 0.556352 
 7.781761 
 
 
 14 
 119943.24 
 156547.42 
 256512.92 
 Rangpur 
 132602.65 
 0.725394 
 8.626968 
 
 
 15 
 165349.20 
 122616.84 
 261776.23 
 Dhaka 
 129917.04 
 1.000000 
 10.000000 
 
 
 16 
 78013.11 
 121597.55 
 264346.06 
 Ctg 
 126992.93 
 0.471808 
 7.359041 
 
 
 17 
 94657.16 
 145077.58 
 282574.31 
 Dhaka 
 125370.37 
 0.572468 
 7.862341 
 
 
 18 
 91749.16 
 114175.79 
 294919.57 
 Rangpur 
 124266.90 
 0.554881 
 7.774406 
 
 
 19 
 86419.70 
 153514.11 
 NaN 
 Dhaka 
 122776.86 
 0.522650 
 7.613248 
 
 
 20 
 76253.86 
 113867.30 
 298664.47 
 Ctg 
 118474.03 
 0.461169 
 7.305843 
 
 
 21 
 78389.47 
 153773.43 
 299737.29 
 Dhaka 
 111313.02 
 0.474084 
 7.370422 
 
 
 22 
 73994.56 
 122782.75 
 303319.26 
 Rangpur 
 110352.25 
 0.447505 
 7.237524 
 
 
 23 
 67532.53 
 105751.03 
 304768.73 
 Rangpur 
 108733.99 
 0.408424 
 7.042118 
 
 
 24 
 77044.01 
 99281.34 
 140574.81 
 Dhaka 
 108552.04 
 0.465947 
 7.329736 
 
 
 25 
 64664.71 
 139553.16 
 137962.62 
 Ctg 
 107404.34 
 0.391080 
 6.955398 
 
 
 26 
 75328.87 
 144135.98 
 134050.07 
 Rangpur 
 105733.54 
 0.455574 
 7.277872 
 
 
 27 
 72107.60 
 127864.55 
 353183.81 
 Dhaka 
 105008.31 
 0.436093 
 7.180464 
 
 
 28 
 66051.52 
 182645.56 
 118148.20 
 Rangpur 
 103282.38 
 0.399467 
 6.997334 
 
 
 29 
 65605.48 
 153032.06 
 107138.38 
 Dhaka 
 101004.64 
 0.396769 
 6.983846 
 
 
 30 
 61994.48 
 115641.28 
 91131.24 
 Rangpur 
 99937.59 
 0.374931 
 6.874653 
 
 
 31 
 61136.38 
 152701.92 
 88218.23 
 Dhaka 
 97483.56 
 0.369741 
 6.848705 
 
 
 32 
 63408.86 
 129219.61 
 46085.25 
 Ctg 
 97427.84 
 0.383485 
 6.917423 
 
 
 33 
 55493.95 
 103057.49 
 214634.81 
 Rangpur 
 96778.92 
 0.335617 
 6.678083 
 
 
 34 
 46426.07 
 157693.92 
 210797.67 
 Ctg 
 96712.80 
 0.280776 
 6.403879 
 
 
 35 
 46014.02 
 85047.44 
 205517.64 
 Dhaka 
 96479.51 
 0.278284 
 6.391419 
 
 
 36 
 28663.76 
 127056.21 
 201126.82 
 Rangpur 
 90708.19 
 0.173353 
 5.866764 
 
 
 37 
 44069.95 
 51283.14 
 197029.42 
 Ctg 
 89949.14 
 0.266527 
 6.332633 
 
 
 38 
 20229.59 
 65947.93 
 185265.10 
 Dhaka 
 81229.06 
 0.122345 
 5.611723 
 
 
 39 
 38558.51 
 82982.09 
 174999.30 
 Ctg 
 81005.76 
 0.233194 
 6.165972 
 
 
 40 
 28754.33 
 118546.05 
 172795.67 
 Ctg 
 78239.91 
 0.173901 
 5.869503 
 
 
 41 
 27892.92 
 84710.77 
 164470.71 
 Rangpur 
 77798.83 
 0.168691 
 5.843455 
 
 
 42 
 23640.93 
 96189.63 
 148001.11 
 Ctg 
 71498.49 
 0.142976 
 5.714879 
 
 
 43 
 15505.73 
 127382.30 
 35534.17 
 Dhaka 
 69758.98 
 0.093776 
 5.468878 
 
 
 44 
 22177.74 
 154806.14 
 28334.72 
 Ctg 
 65200.33 
 0.134127 
 5.670633 
 
 
 45 
 1000.23 
 124153.04 
 1903.93 
 Dhaka 
 64926.08 
 0.00

In [80]:
import numpy as np

d = np.linspace(1, 10000, num = 10000, axis=0)

ad_fit_admimistration = m_.fit_transform(df[['Administration']])

ad_fit_admimistration

(10000,)

In [81]:
# Features Transformation Standarization
from sklearn.preprocessing import StandardScaler

s_s = StandardScaler()

In [85]:
s_s_1 = s_s.fit_transform(df[['Marketing Spend']]) # combined 

s_s_1

array([[ 0.89791312],
 [ 1.95586034],
 [ 1.75436374],
 [ 1.55478369],
 [ 1.5049372 ],
 [ 1.27980001],
 [ 1.34006641],
 [ 1.24505666],
 [ 1.03036886],
 [ 1.09181921],
 [ 0.62039825],
 [ 0.59308542],
 [ 0.44325987],
 [ 0.4020776 ],
 [ 1.01718075],
 [ 2.01641149],
 [ 0.0944412 ],
 [ 0.46072013],
 [ 0.39672494],
 [ 0.27944165],
 [ 0.05572609],
 [ 0.1027236 ],
 [ 0.00600658],
 [-0.13620072],
 [ 0.0731146 ],
 [-0.19931169],
 [ 0.0353702 ],
 [-0.03551899],
 [-0.16879272],
 [-0.17860854],
 [-0.25807437],
 [-0.27695823],
 [-0.22694868],
 [-0.40112892],
 [-0.60068212],
 [-0.60974994],
 [-0.99157015],
 [-0.65253231],
 [-1.17717755],
 [-0.77382036],
 [-0.98957702],
 [-1.00853372],
 [-1.10210556],
 [-1.28113364],
 [-1.13430539],
 [-1.60035036],
 [-1.59341322],
 [-1.62236202],
 [-1.61043334],
 [-1.62236202]])

In [96]:
# Features Transformation Robust Scaler
from sklearn.preprocessing import RobustScaler

r_b = RobustScaler()

r_b_0 = r_b.fit_transform(df[['Marketing Spend']])
r_b_0

array([[ 0.67253009],
 [ 1.45211292],
 [ 1.3036336 ],
 [ 1.15656655],
 [ 1.11983554],
 [ 0.95393588],
 [ 0.99834513],
 [ 0.9283341 ],
 [ 0.77013442],
 [ 0.8154161 ],
 [ 0.46803423],
 [ 0.44790788],
 [ 0.33750405],
 [ 0.30715756],
 [ 0.76041632],
 [ 1.49673201],
 [ 0.08046566],
 [ 0.35037021],
 [ 0.30321327],
 [ 0.21678926],
 [ 0.05193717],
 [ 0.08656882],
 [ 0.01529973],
 [-0.08949034],
 [ 0.06475046],
 [-0.13599571],
 [ 0.03693728],
 [-0.01529973],
 [-0.11350681],
 [-0.12073992],
 [-0.1792969 ],
 [-0.19321209],
 [-0.15636092],
 [-0.28471131],
 [-0.43175858],
 [-0.43844049],
 [-0.71979714],
 [-0.46996607],
 [-0.85656799],
 [-0.55934112],
 [-0.71832843],
 [-0.7322973 ],
 [-0.80124875],
 [-0.93317142],
 [-0.82497625],
 [-1.16839665],
 [-1.16328479],
 [-1.18461665],
 [-1.17582662],
 [-1.18461665]])

In [99]:
# Features Transformation MaxAbsolute
from sklearn.preprocessing import MaxAbsScaler

m_a_s = MaxAbsScaler()

m_a_s_0 = m_a_s.fit_transform(df[['Marketing Spend']])

m_a_s_0



array([[0.69261666],
 [0.98335946],
 [0.92798459],
 [0.87313643],
 [0.85943772],
 [0.797566 ],
 [0.81412828],
 [0.7880179 ],
 [0.72901786],
 [0.74590551],
 [0.61635061],
 [0.60884455],
 [0.56766982],
 [0.55635219],
 [0.72539353],
 [1. ],
 [0.47180821],
 [0.57246821],
 [0.55488118],
 [0.52264964],
 [0.46116861],
 [0.47408436],
 [0.4475048 ],
 [0.40842369],
 [0.46594728],
 [0.39107967],
 [0.45557444],
 [0.43609283],
 [0.39946683],
 [0.39676926],
 [0.37493063],
 [0.36974101],
 [0.38348453],
 [0.33561668],
 [0.2807759 ],
 [0.2782839 ],
 [0.17335288],
 [0.26652654],
 [0.12234465],
 [0.23319442],
 [0.17390063],
 [0.16869099],
 [0.14297577],
 [0.09377566],
 [0.13412668],
 [0.0060492 ],
 [0.00795565],
 [0. ],
 [0.00327821],
 [0. ]])